### ISSUE TITLE
💾 Кэширование ответов 💾

### ISSUE THREAD

**Issue by dura0ok** [Concert-Mate/Music-Service#6]
- Сделать кэширование ответов через Redis
- Описать здесь насколько закэширован каждый endpoint

**Comment by llirik42** [comment]
Сделал кеширование

Список концертов исполнителя кэшируется на одну минуту, список исполнителей по трек-листу - на 10 минут.

**Comment by llirik42** [comment]
@dura0ok

**Comment by dura0ok** [comment]
Имба, 600 это в чем кэширование? Милисекунды?
Мб это вынести в конфиг?

**Comment by llirik42** [comment]
> Имба, 600 это в чем кэширование? Милисекунды? Мб это вынести в конфиг?

Всё в секундах - это стандарт индустрии)

**Comment by llirik42** [comment]
> Имба, 600 это в чем кэширование? Милисекунды? Мб это вынести в конфиг?

Ну можно и вынести, ща

**Comment by dura0ok** [comment]
> > Имба, 600 это в чем кэширование? Милисекунды? Мб это вынести в конфиг?
> 
> Всё в секундах - это стандарт индустрии)

ваще не очевидно)
